### ISSUE TITLE
Android SDK version

### ISSUE THREAD

**Issue by SWGAKamui** [jbotsim/JBotSim#16]
Si l'on souhaite écrire une version Android pour une SDK minimum de 19 (4.4 Kit-Kat), il y a une incompatibilité avec la fonction : Files.readAllBytes() et Paths.get(filename) (ligne : 1077 Topology.java)
Le minimum pour ces fonctions est la SDK 26 (8 Oreo, la dernière en date).

**Comment by remikey** [comment]
Hello @SWGAKamui . Calls to these methods have been removed from the `jbotsim-core` during the refactoring which preceded the `1.0` version.
An android-dedicated `FileManager` class should handle file access.
