### ISSUE TITLE
Properties and PropertyListener

### ISSUE THREAD

**Issue by pictavien** [jbotsim/JBotSim#22]
Hi,

I have two suggestions:
1/ rename _Properties by Properties or PropertyContainer, but at least remove the _ character
2/ in order to be consistent with others listener, rename the listener method by onPropertyChanged.

**Comment by acasteigts** [comment]
Hi Gerald,
It sounds reasonable indeed. Remi is currently restructuring a large part of the code, so I assigned it to him.
Thanks for the suggestion,

**Comment by acasteigts** [comment]
Or perhaps this issue should remain open until Remi pushes the corresponding commit... (reopened)

**Comment by remikey** [comment]
Enhancement applied in branch fix/22-properties-class-refacto ( 4976a67b54fb6b995bf1a8a1c7d702d168492dcd ). Ready to be merged.

**Comment by remikey** [comment]
Merged into `master`.
