### ISSUE TITLE
JTopology resizing does not resize the Topology

### ISSUE THREAD

**Issue by remikey** [jbotsim/JBotSim#25]
Currently, when the user resizes the `JViewer`, its `JTopology` is properly resized but the related `Topology` is not. It should!

**Comment by remikey** [comment]
Could not reproduce this behavior on current develop (6c7950c45f6964bfbf9c2f7adddd84b037bf4748).
Indeed, when the `JViewer` is resized, it updates the dimensions of `Topology` inside the `JTopology`. See : https://github.com/acasteigts/JBotSim/blob/6c7950c45f6964bfbf9c2f7adddd84b037bf4748/lib/jbotsim-ui-swing/src/main/java/io/jbotsim/ui/JViewer.java#L116

However, I suggest to move this inside `JTopology`. Somebody a `JTopology` without a `JViewer` would encounter a bug. @acasteigts , what do you think?

**Comment by acasteigts** [comment]
OK with the suggestion.

**Comment by remikey** [comment]
@acasteigts and @remikey have raised the fact that some computation *could* be re-executed upon resize (e.g. links resolution). Right now, we don't see any particular reason to do it.

**Comment by remikey** [comment]
Merged into develop.
