### ISSUE TITLE
Remove apps/test-classes/out/ from repo

### ISSUE THREAD

**Issue by pictavien** [jbotsim/JBotSim#31]
Hi,

A build directory,  apps/test-classes/out/,  has been pushed into the repo.

**Comment by remikey** [comment]
My bad. It's fixed.
`out` directories on the 3 first levels should now be ignored by git. I have not included put a strong ignore on `out/` to avoid clash on possible package name.

@pictavien : please tell me if there is something else.

**Comment by pictavien** [comment]
Good news... :)

**Comment by remikey** [comment]
Not merged, not closed!

**Comment by pictavien** [comment]
Oups...

**Comment by remikey** [comment]
Merged into develop. (waiting for merge into master before closing)
