### ISSUE TITLE
(Deprecate) Remove Node.setIntColor

### ISSUE THREAD

**Issue by remikey** [jbotsim/JBotSim#33]
As for `Node.setRandomColor`, which as been deprecated in favor of a `Color` method, `Node.setIntColor` and `Node.getIntColor` should be deprecated:
* `Node.setIntColor`: must be deprecated and the dedicated code should be moved to `Color` and improved if possible
* `Node.getIntColor` : must be deprecated, `Node.getColor` should be used instead.

**Comment by remikey** [comment]
Applied. In particular:
  
* `Node.setIntColor` and `Node.getIntColor` are deprecated;
* `Color Color.getIntColor(n)` (`int` parameter) will return the same value from one run to another;
* `int Color.getIntColor()` (no parameter) tries to return the index of the current Color object in the `basicColors` array and returns -1 if not found;
* new method `Color.getRandomColor(Random)` allows to generate a `Color` with the provided `Random`
* `Color.equals` and `Color.hashCode` have been provided for test purpose

**Comment by remikey** [comment]
After discussion with @acasteigts , some renaming/changes:
* `Color Color.getIntColor(int)` is now `Color Color.getColorAt(int)`
* `int Color.getIntColor()` is now `int Color.indexOf(Color)`, and is `static`
* `Color.getBasicColors()` in now `Color.getIndexedColors()`

**Comment by acasteigts** [comment]
Fine by me. Please rebase and merge @remikey.

**Comment by remikey** [comment]
Rebased and merged into `develop`.

**Comment by remikey** [comment]
***Update:*** it has eventually been decided to remove all deprecated methods before `1.0.0` release.

Applied in `develop`.
Migration information will be available in the changelog.

**Comment by remikey** [comment]
Merged into `master`.
