### ISSUE TITLE
allow to use TopologyGenerators with any kind of node model

### ISSUE THREAD

**Issue by darrivau** [jbotsim/JBotSim#40]
In `TopologyGenerator` only "default" mode of `Node` is used to generate the topologies. Is it possible to add a `String` parameter to every static `generateXXX` functions that could be "default" by default but could be used to specify another `Node` model?

**Comment by remikey** [comment]
Merged into `develop`.

What's been done:
* created `Topology.DEFAULT_NODE_MODEL_NAME` constant for external classes use
* renamed `topology.TopologyGenerator` into `topology.TopologyGenerators`
* removed `topology.TopologyGeneratorFactory` and exposed its inner generators in `topology.generators.*`

Note:
* the current package naming might be modified later

**Comment by remikey** [comment]
Merged into `master`.
