### ISSUE TITLE
Add a die() method to class Node

### ISSUE THREAD

**Issue by acasteigts** [jbotsim/JBotSim#45]
A node should be able to quit the topology. I suggest to add a die() method in class Node. 
The node should not remove itself in this method, but rather set a boolean that the topology will process in the end of the round (i.e. in the removal occurs in the onClock method of the topology).

**Comment by remikey** [comment]
Merged into `develop`:
* `Node.die()` sets a boolean used by the `Topology` at the end of its `onClock()`
* `Node.isDying()` is available:
   * `true` if the `Node` either dying or already dead.
   * `false` otherwhise
* a dying `Node` can't be "revived"

**Comment by remikey** [comment]
Merged into `master`.
