### ISSUE TITLE
References to icons

### ISSUE THREAD

**Issue by pictavien** [jbotsim/JBotSim#46]
In order to use JBotSim icons the client code needs to specify the full path of the file. A class Icons that gathers these paths as static Strings should ease the use of this library and prevent errors when writing paths.

**Comment by acasteigts** [comment]
This would be lovely! Currently the usage of the setIcon method is rather unfriendly.
Note that currently, the class Color does a similar job and is singular (not "Colors"). We could indeed consider a class called "Icon" that contains a number of constant icons *and* makes it possible to create one from a given path. The only drawback that I see is that this class would need to be in the core (not ui). This is fine with me so long as it does not use any graphical component (only storage of information, to be used later by the graphical components).

This being said, we should discuss whether this change is realistic for v1.0.0

**Comment by pictavien** [comment]
The idea was not to create a class for icons since, from Nodes point of view, icons are only strings. Actually the name of the class "Icons" is misleading; perhaps IconLibrary is a better choice.

**Comment by acasteigts** [comment]
I know :-). I was actually wondering if making it a class could have some utility. E.g. encapsulating a few other things like the icon size. Just a comment, I don't have a strong opinion so far.

**Comment by remikey** [comment]
As a complement to #26 , I will create an `io.jbotsim.ui.icons.Icons` class with constant for the provided icons paths.

**Comment by remikey** [comment]
Merged into `release/1-0-0`.

**Comment by remikey** [comment]
Merged into `master`.
