### ISSUE TITLE
getLinks semantics

### ISSUE THREAD

**Issue by pictavien** [jbotsim/JBotSim#49]
Topology objects have getLinks methods. Among them:
- getLinks() returns not directed links.
- getLinks(boolean directed) returns directed or not directed links according to the its parameter.
The name of the first one is misleading it suggests an accessor for all kinds of links; either directed or not. Perhaps we should use getUndirectedLinks() (and obviously getDirectedLinks()).

**Comment by acasteigts** [comment]
I agree. The initial philosophy of this method, and many others, was that a default version must exist with no parameters, corresponding to the most frequent use (here undirected links). While this worked well for other methods, this particular method has proved to be misleading for several users. Thus your suggestion is relevant.

OK to add two methods getUndirectedLinks() and getDirectedLinks(). The former getLinks() method should remain as a deprecated method, the code be transferred (with as few changes as possible) to the new methods, and getLinks() should now call the new ones.

**Comment by remikey** [comment]
merged into `develop`.
