### ISSUE TITLE
gradle javadoc produces warnings and errors

### ISSUE THREAD

**Issue by pictavien** [jbotsim/JBotSim#66]
When I run  `gradlew javadoc`, I get following errors (??? means some character code):
- error: unmappable character (???) for encoding US-ASCII
- error: tag not supported in the generated HTML version: tt

**Comment by pictavien** [comment]
To remember <tt> tags are accepted by jdk 8 but not by jdk 12.  No idea on what happens for other intermediate versions.

**Comment by remikey** [comment]
Review done directly with @pictavien . 
Merged into `develop`.
