### ISSUE TITLE
PlainTopologySerializer.importFromString() always clears Topology

### ISSUE THREAD

**Issue by remikey** [jbotsim/JBotSim#72]
`PlainTopologySerializer.importFromString()` currently clears the `Topology`.

I suggest to remove this call to `topology.clear()` since:
* the other implementations of `TopologySerializer` don't clear the `Topology` 
* the `JViewer` has a popup which give the user the choice to clear it or not (incoherent flow)
* it would be more convenient when setting up an experiment programmatically

**Comment by remikey** [comment]
@acasteigts , do you agree?

**Comment by acasteigts** [comment]
Yes (sorry for the lag).

**Comment by remikey** [comment]
merged in `develop`
