### ISSUE TITLE
Add a Plus (Target) icon

### ISSUE THREAD

**Issue by acasteigts** [jbotsim/JBotSim#73]
It would be nice to add the following icon to the `Icons` class after renaming it as "target.png":

https://www.labri.fr/perso/acasteig/teaching/algomob/practice/files/_target.png

**Comment by remikey** [comment]
This image is fairly simple and could be seen as a "plus" or simply a "cross". "target" seems tied to one specific usage.
I suggest naming the png `cross.png` or `plus.png` and providing the following constants:
* `Icons.CROSS`
* `Icons.PLUS`
* `Icons.TARGET`

What do you thing @acasteigts ?

**Comment by acasteigts** [comment]
OK for `plus.png` and `Icons.PLUS`. For now, let us use a single constant per icon. Thanks.

**Comment by remikey** [comment]
merged into `develop`.
