### ISSUE TITLE
Right-click-created Links orientation

### ISSUE THREAD

**Issue by remikey** [jbotsim/JBotSim#77]
It is possible to manually create a wired link between two nodes (start a right click on the first and drag to the second before releasing the button).

This feature currently always creates links with the default values of `Link`; namely *undirected* and *wired*.

## Orientation

When using a *directed* `Topology`, I find strange to create an *undirected* `Link`. 

I suggest that the orientation be determined using `Topology.getOrientation()`.

## Mode

I think that we would not have much benefit  in creating wireless links using this feature. It would even be strange. 

I suggest we leave that unchanged (still use the default value in `Link`).

**Comment by acasteigts** [comment]
I agree for orientation. And yes, I also agree that it does not really make sense to create wireless links manually, so these links should be wired.

**Comment by remikey** [comment]
merged into `develop`.
