### ISSUE TITLE
TikzTopologySerializer does not export directed links

### ISSUE THREAD

**Issue by remikey** [jbotsim/JBotSim#80]
> Creating issue specifically for `TikzTopologySerializer`. #53 mentions several.

`TikzTopologySerializer` only exports data. No background compatibility needed. Just make sure the result is valid in TikZ.

**Comment by remikey** [comment]
In branch `fix/80-tikztopologyserializer-orientation`:
* Unit tests added with the same input files as for the `DotTopologySerializer`  for regression testing
* Partly refactored the existing code to ease modifications
* Added **directed links support** (+ unit test)
* Enhanced/Fixed the color management which did not work well

@pictavien , would you mind having a look?

**Comment by pictavien** [comment]
Hi @remikey,

Thanks for this contribution that should be useful to LaTeX users ! 

First two remarks:
- Perhaps could we share `dot` input files between test suites.
- For the record, remember to update ChangeLog.

Regarding the class `TikzTopologySerializer`: 
* Line 96, I think there is a bug. The result of exportSensingRange is not concatenated with the final result. You should also add a test that check the translation of sensing ranges.   
* In `exportTopology(topology, scale)`, the domain of `scale` is not clear (the same remark holds for Dot serializer). For instance, to reduce the size of the final drawing should we specify 50 (a percentage) or 0.5 (say, a scale factor). As discussed with you, a first solution is to make this method private.
* Line 126, the computation of `y` seems to refer to the default height (?) of topologies (i.e. `600`). Does not coordinates be computed w.r.t. to topology dimensions ?
 
Then I have some remarks that are more a matter of taste than actual issues:
* getStringColor(): Fixed colors could be gathered into a static Map<String,Color>. 
* In exportXXXX() :
    * Some constants could be declared as static final members (`sr / 5.0`, `gray!40`, ...) .  
    * There is no performance issue but private methods `exportSomething()` could use a `StringBuilder` object allocated in `exportTopology` instead of concatenations of `String`s.

Regarding tests, all seem fine except that, as discussed above, it misses a test for sensing ranges.

**Comment by remikey** [comment]
What has been done with this review:
* fixed the `exportSensingRange` issue (+ test)
* made modifications so that *scale* actually be a *scale factor*
  * a new constructor and constants have been provided to clarify this behavior
  * `exportToString(Topology, scale)` is now protected 
* the `Topology`'s height is now used to reverse the Y axis
* use a `StringBuilder` 
* updated the unit tests accordingly
* updated the changelog

What has **not** been done with this review:
* unification of the unit test data
  To my opinion, this job is more general and needs someone to think it globally.
* the TikZ known colors are still arranged in a if/else manner. 
* some TikZ related constants Strings might be  put in constants, but I did not want to make this too complicated

**Comment by pictavien** [comment]
Thanks. I think we can close the issue after squashing your changes.

**Comment by remikey** [comment]
Squashed and merged into `develop`.
