### ISSUE TITLE
Add a transparent icon in the default icons.

### ISSUE THREAD

**Issue by acasteigts** [jbotsim/JBotSim#84]
Could you please add a transparent icon in the default icons, with a name like `Icons.EMPTY`?

**Comment by remikey** [comment]
What's been done in branch `feature/84-transparent-icon`:
* added a (standard) 32x32 transparent icon named `transparent.png`, accessible via `Icons.TRANSPARENT`

**Comment by remikey** [comment]
merged into `develop`.
