### ISSUE TITLE
ClockManager behavior

### ISSUE THREAD

**Issue by remikey** [jbotsim/JBotSim#86]
One of JBotSim's default behavior can be stated as follows:
_The `MessageEngine` should be the first thing to be executed during a round, so that messages sent during round n are properly delivered at the beginning of round n+1._

In this statement, a round can be defined as the period during which return values from `Topology.getTime()` are the same value.

With the current implementation of the `ClockManager` has let me create a message (using a mouse selection) containing its creation round  `r = Topology.getTime()` which has been delivered at a date equal to `r`.
Although marginal, this behavior should not happen.

Please modify the `ClockManager` so that:
* this can't happen anymore
* the first round number remain 0
* the first onClock() and onStart() are called on round 0

Also, please document those behaviors.

**Comment by remikey** [comment]
Modifications pushed in branch `fix/86-clockmanager-behavior`:
* `ClockManager`: 
   * swapped time increment and the call to the `Scheduler` in order to be sure that the `MessageEngine` be the first thing to be called in a round.
   * added a `boolean` in order to make sure that `onStart()` and the first `onClock()` calls are done during round `0`.
* `ClockManagerTest`: new UT class in order to document and enforce the `onStart`/`onClock` behavior.
* `ClockManagerTestMain`: new test class (in module `apps/test-classes`) which  purpose is to check/showcase behaviors linked to the `ClockManager`.

**Comment by remikey** [comment]
@pictavien , @acasteigts , would you please have a look?

**Comment by pictavien** [comment]
Hi @remikey,

I attached comments directly in your commits. Note that creation of nodes increments time (see my comment in ``ClockManager``. Regarding ``ClockManagerTest``:
* some comments could make its purpose more clearer.
* since clocks runs in separate threads, perhaps we could have a similar test with an asynchronous
clock, and invocations of `pause` and `resume' ?

**Comment by remikey** [comment]
@pictavien , I think I have tackled every remark (see replies to comments) but one.

I agree that being able to use (asynchronous) threads to test `pause()` and `resume()` calls would be nice. However, I can't think of a simple way to test this, and I am not sure what of should be tested. If it's ok with you, I suggest creating a dedicated issue to test specify what should be done.

**Comment by pictavien** [comment]
Hi @remikey,

I think all is ok. The issue can be closed

**Comment by remikey** [comment]
I squashed what could be squashed and merged it into `develop`.
